apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: localhost
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dUQ0NBVUVDQVFBd0ZERVNNQkFHQTFVRUF4TUpiRzlqWVd4b2IzTjBNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2bHorMFJjcGZsQ01hbWY0ZjV1UGhidUJJMGU5N0VodWxaNElQWEtzCklFdzZDajEwSy9OMjZIZG9GQ3pqai9jUkhXNlllSEpDSFBwZXRqWG9EVEloYVFzclNOeWErRTNIVnFaeTNZVCsKTmVIR3JmTE51bjhqQ1dqbXpPUFMyUDNYK1FKcXRtdTNjTWwxVUc4YWl5TnVwZEllVnNXeHJDRkljcGl5dk11WgpSQ20yTG9WanVyelFBNEVSaE8vSDJ4ei93a3NiL3hZamVHQUpYaTNKTzl4TG5odjhEdStYeFNGekhPdTJWWFphCm5VdHVmOEpxbkxPc0NpVmhoUXprcEc3NVBPckJrZEpEZ0FkVkpyVXNFQVBiU3VseGx6MkRwNzk4YXNRVE5oeUkKOFRCSVVqSUM3NTM5Y0JTMW9CL0dFU3ByRUJlRmRJenY2NE5KUlhaOXJMemkwUUlEQVFBQm9BQXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUUrNjVsc3Y0a1FSc0Z2T1Q0THVaMFlHZXNkWlMxVFhxTFI3Tm5uSFdGWDdDL0NuCklxcVByMUV1NXVoc1VyL2ZIaTNCUFRlclB6RDFHdjVOWi9NMDFCUU56VW4rTWpuRUp4dm5MSkVoTi9CYU1WdWoKM2Q0NEcxZTVXSHNaaUs4ZXArUHRaQ1p6QnV0amIraXdxelM2NmhlMk9Uc0wwNXVKT3VEWUxDZ29NU1cwYWJQbgpUQW0rNWhkLzJlelZhRmVRTXJkOUV0STJHcG1KNkVDUHA4dTdJUDV4Ni9hamJQUzFkS2VQbXNrZ2VhUmlHcEZmClljd2NVK0ZDQ2hJZDFPSmdtYzMzRWRaek5WUVJ0ajdOOWJBSWRnNkk5bHZTZ1c1R1RqZmNXZXBTOFN4YkM5Y2MKQlFRc0NYU3dFOFRTNU1DRnY3WVErZE1YMUpnam1xTkxNakdFTStRPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0=
  signerName: beta.eks.amazonaws.com/app-serving
  usages:
    - digital signature
    - key encipherment
    - server auth
