version: '3.4'

services:
  node:
    image: ${DOCKER_REGISTRY-}node
    build:
      context: .
      dockerfile: Node/Dockerfile

  signedgeservice:
    image: ${DOCKER_REGISTRY-}signedgeservice
    build:
      context: .
      dockerfile: ../SignEdgeService/Dockerfile

